import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="border-b border-white p-4">
          <ul className="flex space-x-4">
            <li>
              <Link href="/" className="text-white hover:underline">
                Home
              </Link>
            </li>
            <li>
              <Link href="/about" className="text-white hover:underline">
                About
              </Link>
            </li>
            <li>
              <Link href="/about/me" className="text-white hover:underline">
                About Me
              </Link>
            </li>
            <li>
              <Link href="/user" className="text-white hover:underline">
                User
              </Link>
            </li>
            <li>
              <Link href="/admin" className="text-white hover:underline">
                Admin
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
